apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::765462516024:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-4Q6J78VFA418
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-03-13T00:34:24Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2021-03-13T00:34:24Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1525"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 8690d8a2-b6ff-439f-835c-3a23d01925e8
